# Generated by Django 4.0.1 on 2022-05-29 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='description',
            field=models.CharField(default='', max_length=1000, verbose_name='Описание'),
        ),
    ]
