# Generated by Django 4.0.1 on 2022-05-29 14:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_alter_event_participants_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='date_start',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2022, 5, 29, 14, 50, 30, 296948, tzinfo=utc), verbose_name='Дата начала'),
            preserve_default=False,
        ),
    ]
